# Generated by Django 3.1.7 on 2021-04-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('latitude', models.DecimalField(decimal_places=25, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=25, max_digits=30)),
                ('unique_squirrel_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('date', models.DateField(verbose_name='date')),
                ('age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=10, null=True, verbose_name='age')),
                ('primary_fur_color', models.CharField(blank=True, choices=[('Gary', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Blank', 'Black')], max_length=20, null=True)),
                ('location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], max_length=20, null=True)),
                ('specific_location', models.CharField(blank=True, max_length=255, null=True)),
                ('running', models.BooleanField(default=False)),
                ('chasing', models.BooleanField(default=False)),
                ('climbing', models.BooleanField(default=False)),
                ('eating', models.BooleanField(default=False)),
                ('foraging', models.BooleanField(default=False)),
                ('other_activities', models.TextField(blank=True, null=True, verbose_name='Other Activities')),
                ('kuks', models.BooleanField(default=False)),
                ('quaas', models.BooleanField(default=False)),
                ('moans', models.BooleanField(default=False)),
                ('tail_flags', models.BooleanField(default=False)),
                ('tail_twitches', models.BooleanField(default=False)),
                ('approaches', models.BooleanField(default=False)),
                ('indifferent', models.BooleanField(default=False)),
                ('runs_from', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Squirrel',
                'verbose_name_plural': 'Squirrel',
                'ordering': ('-date',),
            },
        ),
    ]
